#!/usr/bin/python3


def raise_exception_msg(message=""):
    """A NameError exception with a message is raised."""
    raise NameError(message)
