#!/usr/bin/python3
def raise_exception_msg(message=""):
  """An exception with a message of NameError is raised.""
    raise NameError(message)
